import { useId } from 'react';
import { appConfig } from '@/config/env';
import { Alert } from '@/components/ui/Alert';
import { Button } from '@/components/ui/Button';
import { Card, CardBody, CardHeader } from '@/components/ui/Card';
import { useBackendHealthCheck } from '../api';

/** Masked placeholder. It is not, and must never become, a real key. */
const API_KEY_PLACEHOLDER = '••••••••••••••••••••••••';

export function ApiSettings() {
  const health = useBackendHealthCheck();
  const keyId = useId();

  return (
    <div className="space-y-6">
      <Card>
        <CardHeader title="Backend connection" description="The only real backend call in this build: GET /api/v1/health." />
        <CardBody className="space-y-4">
          <dl className="text-sm">
            <dt className="text-xs text-fg-subtle">API base URL (VITE_API_BASE_URL)</dt>
            <dd className="mt-0.5 font-mono text-fg">{appConfig.apiBaseUrl || 'Same origin (development proxy to 127.0.0.1:8000)'}</dd>
          </dl>
          <Button variant="secondary" onClick={() => health.mutate()} loading={health.isPending}>
            Test connection
          </Button>
          <div aria-live="polite">
            {health.isSuccess && (
              <Alert tone="success" title="Backend reachable">
                {health.data.service} v{health.data.version}: {health.data.message}
              </Alert>
            )}
            {health.isError && (
              <Alert tone="danger" title="Backend unreachable">
                Start the backend on http://127.0.0.1:8000 and try again.
              </Alert>
            )}
          </div>
        </CardBody>
      </Card>

      <Card>
        <CardHeader title="API keys" description="Programmatic access is not available yet." />
        <CardBody className="space-y-3">
          <label htmlFor={keyId} className="text-sm font-medium text-fg">
            Workspace API key (demo placeholder)
          </label>
          <input
            id={keyId}
            type="text"
            readOnly
            disabled
            value={API_KEY_PLACEHOLDER}
            aria-describedby={`${keyId}-hint`}
            className="h-9 w-full rounded-md border border-line bg-surface-muted px-3 font-mono text-sm text-fg-muted"
          />
          <p id={`${keyId}-hint`} className="text-xs text-fg-muted">
            No key exists. Real keys will be generated by the backend, shown once, and never stored in the frontend.
          </p>
          <Button variant="secondary" disabled>
            Generate API key
          </Button>
        </CardBody>
      </Card>
    </div>
  );
}
