import type {
  Agent,
  AgentPermission,
  CapabilityKey,
  PermissionLevel,
  RiskLevel,
  SecurityCheck,
  SecurityCheckStatus,
} from '@/types/domain';
import { demoPeople } from './people';
import { daysAgo, hoursAgo, minutesAgo } from './time';

/*
 * DEMO DATA. Fictional agents used to exercise the UI before the backend
 * exists. Risk scores, verification states and security checks are
 * illustrative, not the output of any real scan.
 */

const perm = (
  capability: CapabilityKey,
  level: PermissionLevel,
  risk: RiskLevel,
  scope: string,
  requiresApproval = false,
): AgentPermission => ({ capability, level, risk, scope, requiresApproval });

const checks = (statuses: [SecurityCheckStatus, SecurityCheckStatus, SecurityCheckStatus, SecurityCheckStatus, SecurityCheckStatus]): SecurityCheck[] => {
  const definitions = [
    { id: 'chk_dependencies', name: 'Dependency vulnerability scan' },
    { id: 'chk_secrets', name: 'Embedded secret detection' },
    { id: 'chk_permissions', name: 'Permission minimisation' },
    { id: 'chk_injection', name: 'Prompt-injection evaluation' },
    { id: 'chk_egress', name: 'Network egress policy' },
  ];
  const detail: Record<SecurityCheckStatus, string> = {
    passed: 'No issues found in the demo assessment.',
    warning: 'Needs review before production use (demo finding).',
    failed: 'Blocking issue in the demo assessment.',
    not_run: 'Not yet evaluated.',
  };
  return definitions.map((d, i) => ({ ...d, status: statuses[i] ?? 'not_run', detail: detail[statuses[i] ?? 'not_run'] }));
};

const denyRest = (granted: AgentPermission[]): AgentPermission[] => {
  const all: CapabilityKey[] = ['web_access', 'api_access', 'file_access', 'database_access', 'tool_calling', 'code_execution', 'email_send'];
  return all.map((capability) => granted.find((p) => p.capability === capability) ?? perm(capability, 'denied', 'low', 'Not granted'));
};

export const demoAgents: Agent[] = [
  {
    id: 'agt_research_scout',
    name: 'Research Scout',
    description: 'Searches approved sources, reads documents and produces cited research briefs. Never writes to external systems.',
    category: 'research',
    tags: ['research', 'citations', 'summaries'],
    version: '2.3.1',
    status: 'active',
    verification: 'verified',
    visibility: 'public',
    riskLevel: 'low',
    riskScore: 18,
    creator: demoPeople.maya,
    owner: demoPeople.maya,
    createdAt: daysAgo(120),
    updatedAt: daysAgo(3),
    lastExecutionAt: minutesAgo(14),
    model: { provider: 'Model gateway', model: 'balanced-large', temperature: 0.2, maxOutputTokens: 4096 },
    tools: ['web_search', 'document_reader', 'citation_formatter'],
    permissions: denyRest([
      perm('web_access', 'restricted', 'medium', 'Allow-listed research domains only'),
      perm('file_access', 'read_only', 'low', 'Shared research folder'),
      perm('tool_calling', 'allowed', 'low', 'Declared read-only tools'),
    ]),
    resourceLimits: { maxRuntimeSeconds: 600, maxMemoryMb: 512, maxTokensPerRun: 60000, maxToolCalls: 40 },
    securityPolicy: { sandbox: 'strict', networkEgress: 'allow_list', allowedDomains: ['arxiv.org', 'docs.example.com'], approvalRequiredFor: ['high', 'critical'], auditLogging: true },
    securityChecks: checks(['passed', 'passed', 'passed', 'passed', 'passed']),
  },
  {
    id: 'agt_threat_triage',
    name: 'Threat Triage',
    description: 'Reviews security alerts, correlates related events and drafts a triage summary with recommended containment steps.',
    category: 'security',
    tags: ['security', 'siem', 'triage'],
    version: '1.8.0',
    status: 'active',
    verification: 'verified',
    visibility: 'organization',
    riskLevel: 'high',
    riskScore: 72,
    creator: demoPeople.omar,
    owner: demoPeople.sam,
    createdAt: daysAgo(210),
    updatedAt: daysAgo(6),
    lastExecutionAt: minutesAgo(3),
    model: { provider: 'Model gateway', model: 'reasoning-large', temperature: 0.1, maxOutputTokens: 8192 },
    tools: ['siem_query', 'ticket_create', 'notify_oncall'],
    permissions: denyRest([
      perm('api_access', 'restricted', 'high', 'SIEM read API and ticketing'),
      perm('database_access', 'read_only', 'medium', 'Alert history (read only)'),
      perm('tool_calling', 'allowed', 'medium', 'Declared triage tools'),
      perm('email_send', 'restricted', 'high', 'On-call distribution list', true),
    ]),
    resourceLimits: { maxRuntimeSeconds: 900, maxMemoryMb: 1024, maxTokensPerRun: 120000, maxToolCalls: 80 },
    securityPolicy: { sandbox: 'strict', networkEgress: 'allow_list', allowedDomains: ['siem.internal.example'], approvalRequiredFor: ['high', 'critical'], auditLogging: true },
    securityChecks: checks(['passed', 'passed', 'warning', 'passed', 'passed']),
  },
  {
    id: 'agt_code_reviewer',
    name: 'Code Review Assistant',
    description: 'Reviews pull requests for correctness and security issues, runs tests in a sandbox and posts review comments.',
    category: 'engineering',
    tags: ['code-review', 'testing', 'github'],
    version: '3.0.2',
    status: 'active',
    verification: 'verified',
    visibility: 'public',
    riskLevel: 'medium',
    riskScore: 44,
    creator: demoPeople.lena,
    owner: demoPeople.lena,
    createdAt: daysAgo(300),
    updatedAt: daysAgo(1),
    lastExecutionAt: hoursAgo(2),
    model: { provider: 'Model gateway', model: 'balanced-large', temperature: 0.3, maxOutputTokens: 8192 },
    tools: ['repo_reader', 'test_runner', 'pr_comment'],
    permissions: denyRest([
      perm('api_access', 'restricted', 'medium', 'Pull request comments only'),
      perm('file_access', 'read_only', 'low', 'Repository checkout'),
      perm('tool_calling', 'allowed', 'low', 'Declared review tools'),
      perm('code_execution', 'restricted', 'high', 'Test suite inside isolated sandbox'),
    ]),
    resourceLimits: { maxRuntimeSeconds: 1200, maxMemoryMb: 2048, maxTokensPerRun: 150000, maxToolCalls: 60 },
    securityPolicy: { sandbox: 'strict', networkEgress: 'none', allowedDomains: [], approvalRequiredFor: ['critical'], auditLogging: true },
    securityChecks: checks(['passed', 'passed', 'passed', 'warning', 'passed']),
  },
  {
    id: 'agt_data_analyst',
    name: 'Data Insights Analyst',
    description: 'Profiles datasets, detects anomalies and produces source-linked reports with the query behind every figure.',
    category: 'data',
    tags: ['analytics', 'sql', 'reporting'],
    version: '2.1.0',
    status: 'paused',
    verification: 'verified',
    visibility: 'private',
    riskLevel: 'medium',
    riskScore: 38,
    creator: demoPeople.priya,
    owner: demoPeople.priya,
    createdAt: daysAgo(160),
    updatedAt: daysAgo(12),
    lastExecutionAt: daysAgo(2),
    model: { provider: 'Model gateway', model: 'balanced-large', temperature: 0.2, maxOutputTokens: 4096 },
    tools: ['sql_readonly', 'chart_renderer', 'notebook_sandbox'],
    permissions: denyRest([
      perm('database_access', 'read_only', 'medium', 'Analytics warehouse (read replica)'),
      perm('file_access', 'read_only', 'low', 'Uploaded CSV files'),
      perm('tool_calling', 'allowed', 'low', 'Declared analysis tools'),
      perm('code_execution', 'restricted', 'high', 'Sandboxed notebook kernel'),
    ]),
    resourceLimits: { maxRuntimeSeconds: 1800, maxMemoryMb: 4096, maxTokensPerRun: 100000, maxToolCalls: 50 },
    securityPolicy: { sandbox: 'strict', networkEgress: 'none', allowedDomains: [], approvalRequiredFor: ['high', 'critical'], auditLogging: true },
    securityChecks: checks(['passed', 'passed', 'passed', 'passed', 'warning']),
  },
  {
    id: 'agt_incident_responder',
    name: 'Incident Responder',
    description: 'Proposes and, after human approval, applies remediation steps for infrastructure incidents.',
    category: 'operations',
    tags: ['incident', 'infrastructure', 'remediation'],
    version: '0.9.4',
    status: 'active',
    verification: 'pending',
    visibility: 'private',
    riskLevel: 'critical',
    riskScore: 88,
    creator: demoPeople.sam,
    owner: demoPeople.omar,
    createdAt: daysAgo(45),
    updatedAt: hoursAgo(20),
    lastExecutionAt: minutesAgo(41),
    model: { provider: 'Model gateway', model: 'reasoning-large', temperature: 0, maxOutputTokens: 8192 },
    tools: ['cloud_inventory', 'runbook_executor', 'status_page_update'],
    permissions: denyRest([
      perm('api_access', 'allowed', 'critical', 'Cloud control-plane APIs', true),
      perm('tool_calling', 'allowed', 'high', 'Declared runbook tools', true),
      perm('code_execution', 'restricted', 'critical', 'Approved runbooks inside sandbox', true),
      perm('web_access', 'restricted', 'medium', 'Status page provider only'),
    ]),
    resourceLimits: { maxRuntimeSeconds: 900, maxMemoryMb: 1024, maxTokensPerRun: 80000, maxToolCalls: 30 },
    securityPolicy: { sandbox: 'strict', networkEgress: 'allow_list', allowedDomains: ['status.example.com'], approvalRequiredFor: ['medium', 'high', 'critical'], auditLogging: true },
    securityChecks: checks(['passed', 'passed', 'failed', 'warning', 'passed']),
  },
  {
    id: 'agt_support_drafter',
    name: 'Support Reply Drafter',
    description: 'Drafts replies to support tickets using the knowledge base. Every outgoing message waits for human approval.',
    category: 'support',
    tags: ['support', 'drafting', 'knowledge-base'],
    version: '1.2.3',
    status: 'active',
    verification: 'verified',
    visibility: 'public',
    riskLevel: 'low',
    riskScore: 24,
    creator: demoPeople.priya,
    owner: demoPeople.lena,
    createdAt: daysAgo(90),
    updatedAt: daysAgo(8),
    lastExecutionAt: hoursAgo(5),
    model: { provider: 'Model gateway', model: 'fast-small', temperature: 0.4, maxOutputTokens: 2048 },
    tools: ['kb_search', 'ticket_read', 'reply_draft'],
    permissions: denyRest([
      perm('api_access', 'restricted', 'medium', 'Helpdesk tickets (read) and drafts (write)'),
      perm('tool_calling', 'allowed', 'low', 'Declared support tools'),
      perm('email_send', 'restricted', 'high', 'Customer replies after approval', true),
    ]),
    resourceLimits: { maxRuntimeSeconds: 300, maxMemoryMb: 512, maxTokensPerRun: 30000, maxToolCalls: 20 },
    securityPolicy: { sandbox: 'standard', networkEgress: 'allow_list', allowedDomains: ['helpdesk.example.com'], approvalRequiredFor: ['high', 'critical'], auditLogging: true },
    securityChecks: checks(['passed', 'passed', 'passed', 'passed', 'passed']),
  },
  {
    id: 'agt_seo_auditor',
    name: 'SEO Auditor',
    description: 'Crawls a site you own and produces a prioritised list of technical SEO fixes.',
    category: 'marketing',
    tags: ['seo', 'crawler', 'audit'],
    version: '0.3.0',
    status: 'draft',
    verification: 'unverified',
    visibility: 'private',
    riskLevel: 'low',
    riskScore: 16,
    creator: demoPeople.maya,
    owner: demoPeople.maya,
    createdAt: daysAgo(5),
    updatedAt: hoursAgo(9),
    lastExecutionAt: null,
    model: { provider: 'Model gateway', model: 'fast-small', temperature: 0.3, maxOutputTokens: 2048 },
    tools: ['site_crawler', 'report_writer'],
    permissions: denyRest([
      perm('web_access', 'restricted', 'medium', 'Verified domains you own'),
      perm('tool_calling', 'allowed', 'low', 'Declared audit tools'),
    ]),
    resourceLimits: { maxRuntimeSeconds: 900, maxMemoryMb: 512, maxTokensPerRun: 40000, maxToolCalls: 200 },
    securityPolicy: { sandbox: 'standard', networkEgress: 'allow_list', allowedDomains: ['www.example.com'], approvalRequiredFor: ['high', 'critical'], auditLogging: true },
    securityChecks: checks(['passed', 'passed', 'not_run', 'not_run', 'warning']),
  },
  {
    id: 'agt_invoice_reconciler',
    name: 'Invoice Reconciler',
    description: 'Matches supplier invoices to purchase orders and flags discrepancies for finance review.',
    category: 'operations',
    tags: ['finance', 'reconciliation', 'erp'],
    version: '1.4.0',
    status: 'disabled',
    verification: 'rejected',
    visibility: 'public',
    riskLevel: 'high',
    riskScore: 67,
    creator: demoPeople.omar,
    owner: demoPeople.priya,
    createdAt: daysAgo(180),
    updatedAt: daysAgo(15),
    lastExecutionAt: daysAgo(16),
    model: { provider: 'Model gateway', model: 'balanced-large', temperature: 0.1, maxOutputTokens: 4096 },
    tools: ['erp_query', 'invoice_parser', 'ledger_update'],
    permissions: denyRest([
      perm('database_access', 'allowed', 'critical', 'ERP ledger (read and write)', true),
      perm('file_access', 'read_only', 'medium', 'Invoice inbox attachments'),
      perm('tool_calling', 'allowed', 'medium', 'Declared finance tools'),
      perm('email_send', 'restricted', 'high', 'Finance team notifications'),
    ]),
    resourceLimits: { maxRuntimeSeconds: 1200, maxMemoryMb: 1024, maxTokensPerRun: 60000, maxToolCalls: 100 },
    securityPolicy: { sandbox: 'standard', networkEgress: 'allow_list', allowedDomains: ['erp.internal.example'], approvalRequiredFor: ['critical'], auditLogging: true },
    securityChecks: checks(['warning', 'passed', 'failed', 'warning', 'passed']),
  },
];
